### ISSUE TITLE
Cannot run os-snap/bin/server.dart

### ISSUE THREAD

**Issue by michalstrelec** [sdeleuze/opensnap-polymer#1]
I was trying to run os-snap/bin/server.dart and received the following error:
Observatory listening on http://127.0.0.1:49485
Unhandled exception:
Uncaught Error: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 49487
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:883)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

Can you please advise what could be the problem?

My environment is:
Mac OS X 10.9.5 (13F34)
Google Chrome 38.0.2125.104
Dart Editor version 1.7.2.release (STABLE)
Dart SDK version 1.7.2

There was no error in the editor and all the packages where downloaded correctly.

**Comment by vadimtsushko** [comment]
Have same error on Windows 8, Dart Editor version 1.8.3 (STABLE). user_server.dart run succesfully though. snap_server.dart break with error:

Observatory listening on http://127.0.0.1:15608
INFO: 2014-12-13 13:57:15.324: Configured interceptor for /.\* : os_common_server.corsInterceptor
INFO: 2014-12-13 13:57:15.327: Configured interceptor for /.\* : os_common_server.mongoInterceptor
INFO: 2014-12-13 13:57:15.332: Found group: os_snap.SnapService
INFO: 2014-12-13 13:57:15.356: Configured target for /snap/ [POST]: os_snap.SnapService.create
INFO: 2014-12-13 13:57:15.360: Configured target for /snap/:id [GET]: os_snap.SnapService.getById
INFO: 2014-12-13 13:57:15.360: Configured target for /snap/received/:userId [GET]: os_snap.SnapService.received
INFO: 2014-12-13 13:57:15.361: Configured target for /snap/sent/:userId [GET]: os_snap.SnapService.sent
INFO: 2014-12-13 13:57:15.365: Configured target for /snap/:id [DELETE]: os_snap.SnapService.delete
INFO: 2014-12-13 13:57:15.411: Running on 0.0.0.0:8082
Unhandled exception:
Uncaught Error: SocketException: OS Error: Удаленный компьютер отклонил это сетевое подключение.

, errno = 1225, address = 127.0.0.1, port = 15612
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
